= VIDEO CLUB
Video Club es un escenario para practicar conceptos de programación orientada a objetos.

== ¿Qué aprenderás?
Aprenderás a diseñar las clases de un programa a partir de un escenario dado, aplicando los conceptos de programación orientada a objetos, así como también, otras buenas prácticas utilizadas en el desarrollo de software.


En una tienda de alquiler de peliculas se desea tener una aplicación que gestione los alquileres de los 
DVDs. 
 
Un cliente puede alquilar una o varias peliculas(DVD) por un tiempo especifico, hay varios tipos de peliculas que el cliente puede alquilar, estas son: INFANTILES, NORMALES  Y NOVEDAD. 

El cliente debe pagar un precio por el alquiler de la misma. 

Sobre el cliente nos interesa saber el nombre, la cantidad de peliculas que desea alquilar  y 
el dinero que tiene que pagar por las peliculas alquiladas. El video club cobra 70 pesos por peliculas normales, 80 pesos por novedad y 60 pesos por peliculas infantiles. Si el cliente pasa de 2 días con una pelicula normal  y  de 3 dias con una pelicula infantil,  se le cobra 5 pesos por cada dia que pasa. 
 
También el cliente cuenta con un programa de puntos, si el cliente alquila una pelicula de tipo novedad por más de 1 días el cliente acomula puntos que luego podrá usar en el alquiler de otra pelicula. 




















&copy; 2022 - Eudris Cabrera
Contenido creado bajo licencia CC BY-NC-SA 4.0
https://creativecommons.org/licenses/by-nc-sa/4.0/